### ISSUE TITLE
Create multiple choice flashcards in console.

### ISSUE THREAD

**Issue by wkiger** [d-nedrow/FlashCards#37]
It would add value to our program to have the ability to generate random answers in our flashcards.  The flash card presentation option would give the user the ability to select options 1-4 with the correct answer placed randomly in those options.  The random answers would all be pulled from the same subject to be in the likeness of the true answer.  I would implement this in a way that the statistic would still be maintained.  Further, this logic can be used for the Graphical User Interface that is still in early development.  I would also do this so the random answers would not be duplicated in the same question.  
<img width="1048" alt="Screen Shot 2019-04-09 at 9 33 43 PM" src="https://user-images.githubusercontent.com/23282379/55845259-2aab0980-5b0f-11e9-962f-514983942fb2.png">

<img width="1030" alt="Screen Shot 2019-04-09 at 9 38 20 PM" src="https://user-images.githubusercontent.com/23282379/55845436-ce94b500-5b0f-11e9-87a2-46605fd53189.png">

The above is a picture of my testing phase.

**Comment by wkiger** [comment]
I obviously "jumped the gun" on this!  I will wrap this up soon.  Let me know if you have any suggestions.

**Comment by d-nedrow** [comment]
Remember you can always push corrections to an open pull request. So if you want me to look at the code before officially accepting it, opening up a pull request is a good way to do that. I'm happy to offer suggestions on your code, whatever state it is in. Thanks for working on this feature.
